# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-14 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_name', models.CharField(max_length=128, verbose_name='\u4fa7\u8fb9\u680f\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='SidebarLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=128, verbose_name='\u4e0b\u7ea7\u540d\u79f0')),
                ('url_name', models.CharField(max_length=512, verbose_name='\u8def\u7531\u540d\u79f0')),
                ('enable', models.IntegerField(blank=True, choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528')], null=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('sidebar_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Sidebar')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoutingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_info', models.CharField(max_length=20480)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
