# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoutingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_info', models.TextField()),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
