# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-23 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'1', '\u65e0\u9700\u5ba1\u6279'), (b'2', '\u4e00\u7ea7\u5ba1\u6279'), (b'3', '\u4e8c\u7ea7\u5ba1\u6279')], default=b'1', max_length=32, verbose_name='\u5ba1\u6279\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u5ba1\u6279\u7ea7\u522b',
                'verbose_name_plural': '\u5ba1\u6279\u7ea7\u522b',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u8282\u65e5\u540d\u79f0')),
                ('start_day', models.DateField(verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'verbose_name': '\u8282\u5047\u65e5',
                'verbose_name_plural': '\u8282\u5047\u65e5',
            },
        ),
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': '\u90ae\u4ef6\u7ec4',
                'verbose_name_plural': '\u90ae\u4ef6\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_projectinfo', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('first_approver', models.ManyToManyField(related_name='project_first_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e00\u7ea7\u5ba1\u6279\u4eba')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.gogroup')),
                ('mail_group', models.ManyToManyField(related_name='project_mail_group', to='publish.MailGroup', verbose_name='\u90ae\u4ef6\u7ec4')),
                ('owner', models.ManyToManyField(related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
                ('second_approver', models.ManyToManyField(related_name='project_second_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e8c\u7ea7\u5ba1\u6279\u4eba')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u521d\u59cb\u5316',
                'verbose_name_plural': '\u9879\u76ee\u521d\u59cb\u5316',
            },
        ),
        migrations.CreateModel(
            name='PublishApprovalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_count', models.CharField(choices=[(b'1', '\u7b2c\u4e00\u6b21\u5ba1\u6279'), (b'2', '\u7b2c\u4e8c\u6b21\u5ba1\u6279')], default=b'1', max_length=32, verbose_name='\u5ba1\u6279\u6b21\u6570')),
                ('approve_status', models.CharField(choices=[(b'1', '\u901a\u8fc7'), (b'2', '\u62d2\u7edd')], default=b'1', max_length=32, verbose_name='\u5ba1\u6279\u72b6\u6001')),
                ('refuse_reason', models.TextField(blank=True, null=True, verbose_name='\u62d2\u7edd\u539f\u56e0')),
                ('first_approve_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7b2c\u4e00\u5ba1\u6279\u65f6\u95f4')),
                ('second_approve_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7b2c\u4e8c\u5ba1\u6279\u65f6\u95f4')),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_first_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u7b2c\u4e00\u5ba1\u6279\u4eba')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u5355\u5ba1\u6279\u8bb0\u5f55',
                'verbose_name_plural': '\u53d1\u5e03\u5355\u5ba1\u6279\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='PublishSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('publish_time', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u5f00\u59cb\u65f6\u95f4')),
                ('tapd_url', models.TextField(verbose_name='TAPD URL')),
                ('sql_before', models.TextField(blank=True, null=True, verbose_name='\u4e8b\u524d\u6267\u884c\u7684SQL')),
                ('sql_after', models.TextField(blank=True, null=True, verbose_name='\u4e8b\u540e\u6267\u884c\u7684SQL')),
                ('consul_key', models.TextField(blank=True, null=True, verbose_name='consul key')),
                ('status', models.CharField(choices=[(b'1', '\u5ba1\u6279\u4e2d'), (b'2', '\u5ba1\u6279\u62d2\u7edd'), (b'3', '\u5ba1\u6279\u901a\u8fc7'), (b'4', '\u5b8c\u6210\u53d1\u5e03'), (b'5', '\u867d\u5ba1\u6279\u901a\u8fc7\uff0c\u4f46\u8d85\u65f6\u672a\u53d1\u5e03'), (b'6', '\u8d85\u65f6\u672a\u5ba1\u6279')], default=b'1', max_length=32, verbose_name='\u53d1\u5e03\u5355\u72b6\u6001')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='\u7d27\u6025\u53d1\u5e03\u539f\u56e0')),
                ('if_browse', models.CharField(choices=[(b'1', '\u5426'), (b'2', '\u662f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u5f71\u54cd\u7528\u6237\u6d4f\u89c8')),
                ('if_order', models.CharField(choices=[(b'1', '\u5426'), (b'2', '\u662f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u5f71\u54cd\u8ba2\u5355\u6d41\u7a0b')),
                ('if_buy', models.CharField(choices=[(b'1', '\u5426'), (b'2', '\u662f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u5f71\u54cd\u5c65\u5355\u6d41\u7a0b')),
                ('approval_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_publishsheet', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('first_approver', models.ManyToManyField(related_name='publishsheet_first_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e00\u7ea7\u5ba1\u6279\u4eba')),
                ('goservices', models.ManyToManyField(related_name='publish_goservices', to='asset.goservices', verbose_name='\u91cd\u542f\u670d\u52a1')),
                ('qa', models.ManyToManyField(related_name='publishsheet_qa', to=settings.AUTH_USER_MODEL, verbose_name='\u6d4b\u8bd5\u4eba')),
                ('reviewer', models.ManyToManyField(related_name='publishsheet_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='code review\u4eba')),
                ('second_approver', models.ManyToManyField(related_name='publishsheet_second_level_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u4e8c\u7ea7\u5ba1\u6279\u4eba')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u5355',
                'verbose_name_plural': '\u53d1\u5e03\u5355',
            },
        ),
        migrations.CreateModel(
            name='TimeSlotLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.CharField(choices=[(b'1', '\u81ea\u5b9a\u4e49\u6a21\u677f'), (b'2', '\u901a\u7528\u6a21\u677f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u901a\u7528\u6a21\u677f')),
                ('start_of_week', models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'1', max_length=32, verbose_name='\u8d77\u59cb\u65e5')),
                ('end_of_week', models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'7', max_length=32, verbose_name='\u622a\u6b62\u65e5')),
                ('start_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4\u70b9')),
                ('end_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4\u70b9')),
                ('approval_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_timeslotlevel', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'verbose_name': '\u65f6\u95f4\u6bb5--\u5ba1\u6279\u7ea7\u522b',
                'verbose_name_plural': '\u65f6\u95f4\u6bb5--\u5ba1\u6279\u7ea7\u522b',
            },
        ),
        migrations.AddField(
            model_name='publishapprovalhistory',
            name='publish_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.PublishSheet'),
        ),
        migrations.AddField(
            model_name='publishapprovalhistory',
            name='second_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_second_approver', to=settings.AUTH_USER_MODEL, verbose_name='\u7b2c\u4e8c\u5ba1\u6279\u4eba'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='timeslot_level',
            field=models.ManyToManyField(related_name='project_timeslotlevel', to='publish.TimeSlotLevel', verbose_name='\u65f6\u95f4\u6bb5-\u5ba1\u6279\u7ea7\u522b'),
        ),
    ]
