# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_auto_20180709_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4\u70b9'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4\u70b9'),
        ),
    ]
