# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_auto_20180711_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_of_week',
            field=models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'7', max_length=32, verbose_name='\u622a\u6b62'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_of_week',
            field=models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'1', max_length=32, verbose_name='\u8d77\u59cb'),
        ),
    ]
