# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_auto_20180704_1553'),
        ('publish', '0010_auto_20180711_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapd_url', models.CharField(max_length=256, verbose_name='TAPD URL')),
                ('publish_date', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('publish_time', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u5f00\u59cb\u65f6\u95f4')),
                ('sql', models.TextField(blank=True, null=True, verbose_name='\u6267\u884cSQL')),
                ('consul_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='consul key')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_publishsheet', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('goservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.goservices')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u5355',
                'verbose_name_plural': '\u53d1\u5e03\u5355',
            },
        ),
    ]
