# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180704_1553'),
        ('publish', '0011_publishsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishsheet',
            name='goservices',
        ),
        migrations.AddField(
            model_name='publishsheet',
            name='goservices',
            field=models.ManyToManyField(related_name='publish_goservices', to='asset.goservices', verbose_name='\u91cd\u542f\u670d\u52a1'),
        ),
    ]
