# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0014_auto_20180712_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishsheet',
            name='approval_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel'),
        ),
    ]
