# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0015_publishsheet_approval_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishsheet',
            name='project_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.ProjectInfo'),
        ),
    ]
