# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0016_publishsheet_project_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishsheet',
            name='approval_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel'),
        ),
    ]
