# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0017_auto_20180713_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishsheet',
            name='refuse_reason',
            field=models.TextField(blank=True, null=True, verbose_name='\u5ba1\u6279\u62d2\u7edd\u539f\u56e0'),
        ),
    ]
