# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0021_auto_20180716_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_week', models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'1', max_length=32, verbose_name='\u8d77\u59cb')),
                ('end_of_week', models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'7', max_length=32, verbose_name='\u622a\u6b62')),
                ('start_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4\u70b9')),
                ('end_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4\u70b9')),
                ('approval_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.ApprovalLevel')),
            ],
            options={
                'verbose_name': '\u65f6\u95f4\u6bb5--\u7ea7\u522b',
                'verbose_name_plural': '\u65f6\u95f4\u6bb5--\u7ea7\u522b',
            },
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='approval_level',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='project_info',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='time_slot',
            field=models.ManyToManyField(related_name='project_timeslot', to='publish.TimeSlotLevel', verbose_name='\u65f6\u95f4\u6bb5-\u5ba1\u6279\u7ea7\u522b'),
        ),
    ]
