# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0022_auto_20180716_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslotlevel',
            options={'verbose_name': '\u65f6\u95f4\u6bb5--\u5ba1\u6279\u7ea7\u522b', 'verbose_name_plural': '\u65f6\u95f4\u6bb5--\u5ba1\u6279\u7ea7\u522b'},
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='timeslot_level',
            field=models.ManyToManyField(related_name='project_timeslotlevel', to='publish.TimeSlotLevel', verbose_name='\u65f6\u95f4\u6bb5-\u5ba1\u6279\u7ea7\u522b'),
        ),
    ]
