# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0023_auto_20180716_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotlevel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_timeslotlevel', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
