# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-16 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0024_timeslotlevel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotlevel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_timeslotlevel', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005'),
        ),
    ]
