# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0025_auto_20180716_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotlevel',
            name='is_global',
            field=models.CharField(choices=[(b'1', '\u5426'), (b'2', '\u662f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u901a\u7528\u6a21\u677f'),
        ),
        migrations.AlterField(
            model_name='timeslotlevel',
            name='end_of_week',
            field=models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'7', max_length=32, verbose_name='\u622a\u6b62\u65e5'),
        ),
        migrations.AlterField(
            model_name='timeslotlevel',
            name='start_of_week',
            field=models.CharField(choices=[(b'1', '\u5468\u4e00'), (b'2', '\u5468\u4e8c'), (b'3', '\u5468\u4e09'), (b'4', '\u5468\u56db'), (b'5', '\u5468\u4e94'), (b'6', '\u5468\u516d'), (b'7', '\u5468\u65e5')], default=b'1', max_length=32, verbose_name='\u8d77\u59cb\u65e5'),
        ),
    ]
