# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0026_auto_20180717_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotlevel',
            name='is_global',
            field=models.CharField(choices=[(b'1', '\u81ea\u5b9a\u4e49\u6a21\u677f'), (b'2', '\u901a\u7528\u6a21\u677f')], default=b'1', max_length=32, verbose_name='\u662f\u5426\u901a\u7528\u6a21\u677f'),
        ),
    ]
