# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0029_auto_20180718_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishsheet',
            name='project_info',
        ),
    ]
