# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0032_auto_20180718_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishsheet',
            name='consul_key',
            field=models.TextField(blank=True, null=True, verbose_name='consul key'),
        ),
    ]
