# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-19 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0033_auto_20180718_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishapprovalhistory',
            name='first_notices',
        ),
        migrations.RemoveField(
            model_name='publishapprovalhistory',
            name='second_notices',
        ),
    ]
